version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:8000"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./public/static:/public/static
      - ./public/media:/public/media
    depends_on:
      - web
  web:
    build: .
    container_name: utransnet-gateway-web
    command: bash -c "python manage.py collectstatic --noinput
                            && python manage.py makemigrations 
                            && python manage.py migrate 
                            && python create_admin_user.py
                            && gunicorn utransnetgateway.wsgi:application -b 0.0.0.0:8080"
    volumes:
      - ./public/static:/public/static
      - ./public/media:/public/media
    depends_on:
      - db
    expose:
      - "8080"
  gateway-trns_bts:
    build: .
    container_name: utransnet-gateway-trns_bts
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py activate_gateway transnet_bitshares"
    depends_on:
      - db
  gateway-bts_trns:
    build: .
    container_name: utransnet-gateway-bts_trns
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py activate_gateway bitshares_transnet"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres